### PR TITLE
Replace one vs all with one vs one; show max either direction.

### PR DESCRIPTION
**Pull request by Alanocallaghan**
Instead of doing a one vs all comparison for each block,
resulting in a lot of repeated comparisons, just
do the unique 1 vs 1 comparisons. This should be faster
for large packages. To handle finding the max, because
I'm too stupid to figure out exactly how you find the max
pairwise based only on the two indices, I filter to find
the max a->b and max b->a similarity. This will produce
a slightly longer list but hopefully should still be
informative because I am also removing the
duplication in output lists
(ie, Block A is most similar to Block B, and Block B is most
similar to Block A).

There may be a smarter way to do this. In fact, it might be
worthwhile keeping all combns and just filtering by
similarity score above x (eg, above 0.6, or above some null
distn calculated based on block size).

### CODE REVIEW

**Comment by russHyde** [comment]
Hi thanks for this. Although I agree that the results should be undirected by default, I think it might be simpler (and faster) to do this by filtering the table returned by `find_best_matches`. In `.one_against_all`, a single codeblock is compared against the set of other codeblocks (in tokenised form); the iteration over the set of codeblocks is handled by C, rather than R (this probably offsets the two-fold increase in the number of comparisons relative to your version that uses map_dfr over all combinations)

In the original implementation I was keen to distinguish source and target: so that in the results, the target block (block_b) was the most similar block to the source block (block a) and every block was present once in the source column. But I doubt anyone would need that source -> target directionality.

Some tests will need changing in / adding to `test_dupree_classes` to bring this together.

Filtering above a certain similarity score should be a separate thing.

I'll do a couple of experiments at home to compare compare speed and report back later.

**Comment by russHyde** [comment]
I've modified the PR.
Where there was a failing test, I've rewritten the test to ensure that only a single-row results from a pair of reciprocally-best-matching code blocks. Where that happens, dupree now ensures that `file_a` <= `file_b` and where the files are the same, that `block_a` <= `block_b`.
This should ensure there's no replication in the returned results but also that the results are returned in a consistent format.

There is something I need to think about before merging this PR, there's something about the two separate uses of group_by-then-select-max at the end of `find_indexes_of_best_matches` that doesn't seem right.

If the results of comparison were
```
block_a   block_b score
A             B           0.9
A             C           0.7
B             C           0.5
```
Then B-C would not be the maximal match for either B or C, but I suspect this row might make it into the results. Will have a think and add more tests

**Comment by russHyde** [comment]
Hi. Thanks for all your help on this. I've added a few tests to prevent code-block duplicates being reported, and to prevent cycles from occurring in the duplication graph (temporarily, I will eventually report all duplicated code-blocks, rather than just the most-similar match for each block). However, to do this, I've reverted the code you wrote. Hope you don't mind. I've mentioned your initial contribution in 
the NEWS file.

All the best

**Comment by russHyde** [comment]
fixes https://github.com/russHyde/dupree/issues/29

**Comment by Alanocallaghan** [comment]
Yeah no worries Russ, was more of a suggestion than a request. Thanks for the package - will hopefully get some use out of it in time. Cheers

**Pull request merged**
